version: 1.0.{build}
branches:
  only:
  - master
build: off
artifacts:
- path: '**\*.aspx'
- path: '**\*.aspx.cs'
- path: '**\*.master'
- path: '**\*.master.cs'
- path: '**\*.config'
- path: '**\*.dll'
- path: '**\*.xml'
- path: '**\*.html'
- path: '**\*.css'
- path: '**\*.js'
- path: '**\*.png'
- path: '**\*.cs'
- path: '**\*.kml'
deploy:
- provider: FTP
  host: 
    secure: lRXTUgMflVVq7hv4gk86rFXXLWdSbw74VZG3KgkCaSLz3ltLmgx2DbDsncMoDbvb
  protocol: ftps
  username: 
    secure: bjwzJRDCwsfxkDOf1Uoxbcr5DbpY/Y064geWYllpoWkFbkGis6HyZInqwsiPgr+KBWAWXicOJ4eNWZH2oGMsRQ==
  password:
    secure: RFPBFH5nVNZIhPnKsmHIKefQs0f7KtOeWTDQaHXWyla12FvBdPZsbBfPgOkirkzhlf2mXDu7Lz3WJXmbWRCRvg==
  folder: /site/wwwroot
  on:
    branch: master
