version: 1.0.{build}
branches:
  only:
  - master
build: off
artifacts:
- path: '**\*.aspx'
- path: '**\*.aspx.cs'
- path: '**\*.master'
- path: '**\*.master.cs'
- path: '**\*.config'
- path: '**\*.dll'
- path: '**\*.xml'
- path: '**\*.html'
- path: '**\*.css'
- path: '**\*.js'
- path: '**\*.png'
deploy:
- provider: FTP
  host:
     secure: 0kziSkQbILcxCj9ZVELOXDNOCWellJ3/+Ulko/QTA3U=
  protocol: ftps
  username: ftp79179158-2
  password:
    secure: amZ10baC8+YOiKkg1B7l3CWwM3YrOlyzVxfyX0yD+2Q=
  on:
    branch: master